### ISSUE TITLE
Blank red-ish images on M1

### ISSUE THREAD

**Issue by PaulMest** [brycedrennan/imaginAIry#122]
Awesome repo! I'm just now getting into some AI/ML stuff and this was a breeze to get started with.

This is likely related to #83. But the comments from the author said that that issue should focus on CUDA. Looks like the NSFW filter is a bit too aggressive?

```
$ imagine "a gray tonkinese cat wearing a pirate hat, cute and fluffy, 3D Model, Unreal Engine, 3D Render, by Pixar Animation Studios" --repeats 10 --seed 0 --model SD-2.0 --steps 75 --caption
Loading model /Users/paul/.cache/huggingface/transformers/24bd254e54b30e83bcbc15efae29f0ef55256fd144823a9437f5956e594f6803.dcd6f0dd97c55495efb8393e64f704f3f398d695965876be0339bf96b93e2b4e onto mps:0 backend...
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 75/75 [00:33<00:00,  2.21it/s]
    Generated caption: a gray cat with green eyes looking at the camera with a plate in the background with a cake on the table in the foreground
        ⚠️  Filtering NSFW image. nsfw score: 0.002
    Image Generated. Timings: conditioning:0.44s sampling:33.97s safety-filter:2.48s total:49.14s
    🖼  [generated] saved to: ./outputs/generated/000024_0_kdpmpp2m75_PS7.5_a_gray_tonkinese_cat_wearing_a_pirate_hat,_cute_and_fluffy,_3D_Model,_Unreal_Engine,_3D_Render,_by_Pixar_Animation_Studios_[generated].jpg
```

![000024_0_kdpmpp2m75_PS7 5_a_gray_tonkinese_cat_wearing_a_pirate_hat,_cute_and_fluffy,_3D_Model,_Unreal_Engine,_3D_Render,_by_Pixar_Animation_Studios_ generated](https://user-images.githubusercontent.com/1721104/204664546-a0401b68-6438-4ed5-80a5-bfee36b1fbf9.jpg)

System details
```
  macOS: Ventura (13.0.1)
  Python: 3.10.3 (not Conda)
  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro18,2
  Model Number:	Z14X000HQLL/A
  Chip:	Apple M1 Max
  Total Number of Cores:	10 (8 performance and 2 efficiency)
  Memory:	64 GB
  System Firmware Version:	8419.41.10
  OS Loader Version:	8419.41.10
```

**Comment by brycedrennan** [comment]
Appreciate that you provided all the details I needed to debug.  Yes the safety filter can be a little aggressive. Some suggestions:
- run at 15 steps. you'll be surprised its not that much different
- pinning the seed while using repeat doesn't make sense since you'll just generate the same image repeatedly
- if you run at 15 steps you can generate images quickly enough that an occasional red image doesn't matter

![image](https://user-images.githubusercontent.com/1217531/204730994-f0f5f79d-65fb-4c09-b173-ce55ab440c0a.png)

The first two images are the one you were trying to generate at 75 steps.  The rest are random seeds at 15 steps.
```bash
imagine "a gray tonkinese cat wearing a pirate hat, cute and fluffy, 3D Model, Unreal Engine, 3D Render, by Pixar Animation Studios" --repeats 10 --model SD-2.0 --steps 15
```

**Comment by AAlon** [comment]
"Yes the safety filter [which I force you to use by default] can be a little aggressive. So try generating 5 times more than you need!"
Yikes.
