### ISSUE TITLE
Unistall to clear all 10 GB space

### ISSUE THREAD

**Issue by alesrebec** [brycedrennan/imaginAIry#298]
On my laptop I don't have a proper GPU and with CPU doing all the heavy-lifting it would be better to remove all the libs.
Is there a simple way to uninstall everything?

`pip-autoremove imaginairy`

only cleared about 4 GB

**Comment by alesrebec** [comment]
I believe I found the rest ~6GB data. 
There are stable diffustion models in _/home/USER/.cache/huggingface/_ which I removed too.

**Comment by brycedrennan** [comment]
Yeah good point that uninstall isn't a great experience as far as recovering disk space. Not sure if that can be fixed in an automatic fashion.  In the meantime, sounds like you're on the right track. I'd delete any of the following if they exist: 
 - ~/.cache/imaginairy
 - ~/.cache/clip
 - ~/.cache/torch
 - ~/.cache/huggingface
